== Selección de la vida de William Lewis

[.salutation]
Mi querido Amigo,

Cuando considero la profundidad y la fuerza del amor al yo en el alma caída del hombre,
desgajada de la unión a la perfecta voluntad de su glorioso Creador;
y el brote casi perpetuo de los deseos orgullosos,
que se ramifican y se extienden desde esta raíz amarga hacia una dirección u otra;
escribir o incluso hablar de nosotros mismos,
me parece un compromiso que requiere de gran vigilancia
y auto humillación. Bajo esta convicción,
he evitado cautelosamente la correspondencia escrita
sobre mis propias experiencias espirituales,
y durante mucho tiempo he creído que sería mejor para todas las
personas de mente espiritual (particularmente las jóvenes) estar
menos ocupadas en ese sentido de lo que suele ser el caso;
pues comprendo que muchas no son lo suficientemente conscientes de los
sutiles estratagemas de aquel que--en una apariencia disfrazada--puede
secretamente despertar deseos en pos de importancia personal,
y un fuerte interés por nosotros en las mentes de nuestros amigos,
al desear que ellos nos consideren personas de gran experiencia religiosa,
aunque profesemos (con palabras) sentimientos de debilidad y nos
clasifiquemos en el rango más bajo en la escuela de Cristo.

Siendo estos mis sentimientos,
no te parecerá extraño que haya sido lento en cumplir con tu pedido
de contarte algo de mis experiencias y movimientos espirituales.
Sin embargo, finalmente tomo mi pluma con ese propósito,
y como el compromiso traerá necesariamente recuerdos de un tipo muy humillante,
espero que sirva como defensa contra los peligros ya aludidos.

Nací el 17 del noveno mes de 1753.
No hay nada muy notable relacionado con mis primeros días que pueda recordar ahora.
Digo '`nada muy notable,`' porque desafortunadamente,
un deseo temprano y una búsqueda de todo lo que hay en el mundo es,
en mayor o menor grado, el curso del corazón de todo hombre natural,
de acuerdo con su temperamento o inclinación particular.
La mía, recuerdo, fue fuertemente atraída por vanidades mentirosas,
cuya participación en ellas estaba limitada sólo por mis escasos recursos,
y por la autoridad paterna que impuso sobre mí una estricta dedicación a los negocios,
en los que fui introducido en mi catorceavo año. Poseía poco de mi educación anterior,
aparte del conocimiento de la escritura y la aritmética,
que era todo lo que mi padre había juzgado necesario para
un simple mecánico (su designación con respecto a mí).

Previo a ese período, que recuerde ahora,
el único efecto del resplandor de la Luz divina en mi oscuro corazón,
era la solemne y notable autoridad de las Sagradas Escrituras,
y la belleza que aparecía ante mi vista de la verdadera vida de santidad,
y la de una total y sincera dedicación a Dios Todopoderoso.
Esto me llevó a admirar mucho, e incluso, a sentir cierto consuelo,
al considerar a Sus antiguos siervos, cuyas vidas estaban totalmente dedicadas a Él;
y a lamentar cómo algunos otros que parecían tener un grado de celo por Su gloria,
quedaron cortos.
Pero a los catorce años,
se sentía perceptiblemente el poder convincente de la preciosa luz,
y la condenación era terriblemente atestiguada en mi búsqueda de
placeres pecaminosos--ninguno de los cuales fue permitido nunca,
sin sentir el temor de aquel ojo, del cual yo sabía y sentía que nada podía ocultarse.
Para disminuir ese terror,
tomé algunas débiles resoluciones de resistir la siguiente vez que fuera tentado,
pero como esas determinaciones fueron principalmente resultado del miedo,
y se recurría a ellas sólo para enfriar la quemante
indignación que sentía arder en mi consciencia,
generalmente fueron quebrantadas en la hora de prueba.
Tales sentimientos continuaron durante un tiempo considerable,
y a veces se albergaba una débil esperanza de salir algún día del
lodo cenagoso en el que había sumergido a mi pobre alma;
pero no se hizo ningún esfuerzo real para romper con mis malos caminos.

La mayor parte de mi tiempo libre lo pasaba leyendo obras de teatro y novelas,
y de ese modo se estimulaba y alimentaba un estado de ánimo perezoso y débil.
Me aficioné sobremanera a la vestimenta,
y cada vez me entregaba más a cualquier cosa que gratificara tal espíritu.
Los libros útiles e instructivos parecían secos e insípidos; los negocios,
y casi todo lo que requería energía mental y atención constante,
se volvieron pesados y fastidiosos.
De esta manera,
incluso el deseo de luchar por liberación pareció desaparecer en gran medida.
Y aunque a veces se despertaba en mí el temor a las
consecuencias de continuar en ese camino,
pensaba que era casi imposible que algo pudiera apartar mis afectos del mundo.
Porque mi pobre mente estaba tan tenazmente en pos del placer presente,
y tan temerosa de que algo lo interrumpiera, que recuerdo muy bien la alarma que sentía,
no fuera a ser que la doctrina predicada por el clérigo de la parroquia en que yo residía,
en el tiempo llamado Navidad,
condenara o entorpeciera nuestra alegría. Porque oíamos predicar que ese tiempo de fiesta
había sido apartado por la Iglesia con el fin de conmemorar piadosamente la misericordia
y el amor de nuestro Padre celestial al enviar a Su amado Hijo al mundo,
para que, al librarnos de sus corrupciones,
nuestros espíritus fueran aptos y estuvieran preparados
para una morada con Él en el reino de luz y pureza.
Ahora bien,
yo sabía que si esta doctrina era verdaderamente creída
y puesta en práctica por la parte anciana de los oyentes,
nuestras alegres reuniones (que eran mi principal alegría
en esa temporada) serían necesariamente suspendidas;
porque aún en ese estado oscuro, y sin recurrir a ninguna doctrina o precepto,
yo sentía convicción interior de la incompatibilidad entre el deseo
de los deleites mundanos y la verdadera hambre espiritual--de hecho,
suponer que ambos pueden subsistir juntos en un mismo corazón,
implica una incongruencia de la mayor magnitud.
No obstante, había un refugio cerca contra dichos temores.
Porque entonces recordaba, que la misma doctrina había sido predicada,
escuchada y admirada muchas veces antes;
pero que siempre había terminado en que tanto el predicador como los oyentes
se iban y continuaban con sus contribuciones para promover el banquete,
el baile, el canto y la diversión. Así se calmaba mi alarma,
con la esperanza de que las cosas seguirían su curso habitual,
y que nosotros continuaríamos '`cantando al son de los instrumentos de cuerda,
bebiendo vino en copas, y ungiéndonos con los mejores ungüentos,`'^
footnote:[Amós 6:5]
sin que nos perturbara ningún temor a futuras aflicciones por nuestra presente comodidad;
o al menos, que por el consuelo derivado de unirnos mano a mano,
fuéramos capaces de silenciar esas preocupaciones a un grado tolerable.

Esa era mi condición en ese período temprano de mi vida.
Continuó sin ninguna alteración significativa hasta
el año 1775 (el vigésimo segundo de mi vida),
cuando fui poderosamente agitado por el Espíritu de Verdad,
y repentinamente formulé en mi corazón,
el propósito sincero de romper con mis pecados y buscar la paz
con mi Dios en un camino de vida verdaderamente religioso.
Inmediatamente después de tomar esta resolución, actué en consecuencia.
Me despojé de mi ropa llamativa y me limité a una cuidadosa moderación
al satisfacer las necesidades reales de la naturaleza--cortando
con todo lo que parecía una indulgencia innecesaria en el comer,
beber, dormir, etc.; en una palabra,
cortando con todo lo que se hacía por mera recreación. Luego me esforcé rigurosamente
por redimir todo el tiempo precioso que me quedaba libre de los asuntos externos,
retirándome a mi dormitorio o asistiendo a un lugar público de adoración.
Oraba en privado fervorosa y tan frecuentemente como podía,
sabiendo muy poco de tales prácticas cristianas en aquel entonces.
Como estaba bastante desinformado sobre las doctrinas,
no tenía ninguna inclinación hacia una secta en particular por
causa de sus principios distintivos o formas de culto público;
pero como por mucho tiempo había tenido una alta opinión
de los Metodistas Wesleyanos por sus reuniones diarias,
frecuenté sus asambleas durante un tiempo.
Después de esto, por la persuasión de un amigo que profesaba otra secta (es decir,
los seguidores de George Whitfield),
me convertí en oyente en el Tabernáculo y rápidamente me uní como miembro
allí. Digo "`rápidamente,`" porque no hubo un examen previo de sus opiniones,
ni una búsqueda seria de la Fuente de sabiduría para recibir dirección.
Por lo que recuerdo de mis sentimientos en ese momento,
estaban tan fuertemente excitados por el objetivo principal de mi nuevo camino--a saber,
la paz con Dios y una esperanza bien fundada de ser admitido por fin en Su reino celestial--que
se dejó muy poco espacio en mi mente para preocuparme por puntos de doctrina.
Tal dulzura acompañó por un tiempo mis ejercicios religiosos,
que me parecía suficiente oír hablar de la misericordia de Dios en Cristo Jesús,
y que una experiencia de ella era alcanzable en este mundo presente.
Y como estas palabras eran expuestas de una manera tan vívida por aquellos predicadores,
eran "`como meollo y grosura`" para mi alma,
y cuando ocasionalmente se introducían otros puntos de doctrina,
hacían muy poca impresión en mí, y por consiguiente,
obtenían muy poca consideración. Sin embargo,
este estado de ánimo poco a poco se vio perturbado,
cuando me preguntaban sobre el motivo por el que había escogido
ese cuerpo de creyentes entre los demás,
y sobre qué fundamento.

Entonces comencé a construir mis opiniones doctrinales religiosas,
que naturalmente coincidían con las de mis hermanos del Tabernáculo,
y en ese sentido me volví tenaz.
Pronto surgió un espíritu sectario, y bajo su influencia,
empecé a escudriñar las Escrituras con el objetivo de recopilar todo lo
que contenían y pudiera interpretarse a favor del sistema calvinista.
Trabajé arduamente contra la fuerza de muchos pasajes bíblicos
que me resultaban imposibles de conciliar con ese sistema,
y luché contra una convicción interna (sin importar cuánto intentara ignorarla)
que se oponía a creer en la parcialidad de Dios y en un pacto de gracia
en Cristo Jesús que sólo se extendía a unas pocas de sus criaturas caídas,
y dejaba al resto perecer eternamente.

Siendo ejercitado de esta manera,
la buena providencia de mi Padre celestial dirigió la atención
de un vecino piadosamente dispuesto hacia mi estado,
quien--muy preocupado por el peligro que yo parecía correr al empaparme de las
doctrinas aludidas--puso en mi mano algunos escritos espirituales profundos,
por medio de los cuales mi mente fue clara y plenamente convencida de mi error.
Pronto desistí de mi alianza con una doctrina que
sólo me había introducido a una determinación sectaria;
y vi claramente que para mantenerla, había resistido mis propias convicciones,
rechazado las claras doctrinas y declaraciones de los profetas,
apóstoles y de Jesucristo mismo,
y abandonado casi por completo todo pensamiento reconciliable con
la creencia en la bondad y justicia del Todopoderoso Dios.
¡Oh, qué idea tan chocante,
que un Dios bueno y misericordioso permitiría que millares
de millares de espíritus inteligentes llegaran a existir,
sin tener ninguna otra cosa delante de ellos sino un doloroso
y fatigoso paso a través del valle de lágrimas,
lleno de dificultades y dolor,
sólo para terminar entrando a un estado aún más repleto de sufrimiento,
donde la aflicción,
el horror y angustia inconcebibles serían su porción por toda la eternidad! ¡Cuán
monstruoso es creer que _cualquiera_ de las criaturas de Dios--por Su irrevocable
designio--tenga tal destino! ¡Cuán indigno pensamiento de Dios es suponer,
que con el propósito secreto de condenar a la mayoría de la raza humana,
comisionó profetas y apóstoles para llamarlos a participar de Su gloriosa naturaleza,
y buscar una herencia en Su bendito reino,
y finalmente envió a Su amado Hijo entre ellos para invitar
a las almas aún más fervientemente a un gozo inefable,
declarando en los términos más claros,
que cualquier incapacidad de recibir Su ofrecimiento se
debe enteramente a una indisposición voluntaria del corazón,
diciendo: "`Y no queréis venir a mí para que tengáis vida`"!^
footnote:[Juan 5:40]

Pero regresemos a mi estado particular.
Liberada de estos grilletes,
mi mente encontró dulce libertad al reconocer el ofrecimiento universal
del amor de Dios en Cristo para con Su criatura el hombre,
al recibir el testimonio apostólico de que Él "`no hace acepción de personas,`"^
footnote:[Hechos 10:34]
y al rechazar toda opinión y doctrina que no estuvieran edificadas sobre este fundamento.
Entonces, las Sagradas Escrituras fueron leídas con apertura de corazón,
y pronto fui convencido de las siguientes verdades:

[.numbered-group]
====

[.numbered]
1+++.+++ Que la obra de la religión es totalmente interna,
y obrada por la operación del Espíritu Santo de Dios.

[.numbered]
2+++.+++ Que la verdadera adoración es también interna,
al consistir principalmente en una humilde postración
del espíritu ante el omnipresente Creador,
quien es "`Dios de los espíritus de toda carne,`"^
footnote:[Números 16:22; 27:16]
"`Dios de cerca, y no Dios de lejos,`"^
footnote:[Jeremías 23:23]
"`en quien vivimos, y nos movemos, y somos.`"^
footnote:[Hechos 17:28]

[.numbered]
3+++.+++ Que el Todopoderoso Dios, en las riquezas de Su misericordia,
ha sembrado en el corazón de todo hombre un don o medida de Su Palabra viva;
una semilla real de Su naturaleza divina y celestial.^
footnote:[La cual puede ser resistida y rechazado,
o "`recibida con mansedumbre`" para la salvación del alma.
Ver Santiago 1:21; Mateo 13:3-9; Juan 1:9; Romanos 1:19]

[.numbered]
4+++.+++ Que el levantamiento de esta "`semilla incorruptible`" hasta
convertirse en un poder dominante de vida en el alma del hombre,
es tan necesario para la verdadera percepción de las cosas espirituales,
como es necesaria la participación de la naturaleza
humana para el conocimiento de las cosas del hombre.
La operación vivificante del Espíritu Santo en y sobre este don indecible,
es lo que le da al alma una renovada sensibilidad de la presencia de Dios,
y es esencial para la realización de la verdadera adoración. Por lo tanto,
esto debe ser reverentemente buscado y esperado, "`para que busquen a Dios,
si en alguna manera, palpando, puedan hallarle,
aunque ciertamente no está lejos de cada uno de nosotros.`"^
footnote:[Hechos 17:27]

[.numbered]
5+++.+++ Que en consecuencia, la fe para la que todas las cosas son posibles,
es algo de una naturaleza mucho más profunda que
la mera aceptación del juicio de verdades o doctrinas,
o un acuerdo con lo que es llamado por muchos,
el "`Plan Evangélico de Salvación,`" o incluso con todo
lo que contiene el credo de la teología sistemática.

====

Los escritos espirituales antes aludidos,
fueron indudablemente usados por el Señor para traer mayor claridad a estas nuevas convicciones,
pero el sello que las estampó plenamente en mi corazón,
fue el testimonio del apóstol en Atenas,
donde expone la verdadera relación de la criatura con su glorioso Creador,
el elevado origen y destino del hombre,
y su consecuente y apropiado ejercicio y glorioso privilegio, a saber: Buscar al Señor,
"`si en alguna manera, palpando, puedan hallarle,
aunque ciertamente no está lejos de cada uno de nosotros; porque en él vivimos,
y nos movemos, y somos.`"
¡Oh, esa expresión: "`si en alguna manera, palpando,
puedan hallarle`"! ¡Cuán fuertemente imprime esto
la necesidad de un profundo vuelco al interior,
en la búsqueda del acceso a la Fuente de pureza y amor!

Con esta visión de las cosas y bajo estas impresiones, la manera de adoración,
así como también la comunicación verbal en el Tabernáculo,
pronto se volvieron insatisfactorias para mí. Entonces empecé a pensar,
y finalmente acudí, a las reuniones de la Sociedad de Amigos,
principalmente porque sus reuniones se llevaban a cabo de
una manera más compatible con mis convicciones que las de
cualquier otra sociedad religiosa de la que tuviera conocimiento;
aunque también tenía algunas expectativas del ministerio entre ellos,
creyendo que aquellos que había sido realmente llamados a la obra,
podían recibir directamente lo que era adecuado a
los estados de aquellos a quienes ministraban.
Las comunicaciones verbales que escuché entre los Amigos fueron directas,
convincentes y muy claras con respecto a muchos puntos que me habían preocupado.
A veces eran profundamente espirituales,
reforzadas con poder y acompañadas de algo que comunicaba a mis
sentimientos que ellas eran el resultado de una experiencia viva.
Todo esto tendió a profundizar mis recientes impresiones,
y comencé a actuar en concordancia con ellas.
En mis horas de retiro, en lugar de cantar,
pronunciar largas listas de peticiones y leer, empecé a esperar en silencio,
con deseos fervientes de solemnidad y postración interior de espíritu ante el Santo,
anhelando ese poder vivificante que contrista y prepara
el corazón para recibir comunicaciones divinas,
y al recibirlas, lo devuelve todo al gran Dador de todo don perfecto.

Al cesar de esta manera de tanta actividad de la criatura,
y enfocar más mi atención hacia lo que pasaba dentro de mi propio pecho,
rápidamente se levantó una dolorosa convicción de que yo en realidad
era (con respecto a las cosas espirituales) un "`desventurado,
miserable, pobre, ciego y desnudo.`"
Aquella preciosa luz que me había visitado previamente con dulces persuasiones,
ahora me atraía al desierto y me mostraba la "`tierra desierta`" de mi propio corazón;
y fue durante ese tiempo, que las obras oscuras de incredulidad e impaciencia,
empezaron a sugerirme que seguramente el Señor me había abandonado.
Entonces empecé a poner en duda la poca experiencia
espiritual que había conocido antes de esto,
y al final consideré que había sido mayormente el efecto de una imaginación apasionada.
La aflicción y la angustia rápidamente ganaron terreno en mi alma,
y me hallé escribiendo cosas amargas contra mí mismo casi continuamente.
Entonces, al rechazar toda esperanza de consuelo, se abrió una puerta para la depresión;
¡oh, ésta se metió en mis mismas venas, y pronto dejé ir toda mi confianza en Dios!
Probé la copa amarga de la desesperación, y al considerarme abandonado por mi Dios,
lloré y sollocé en voz alta desde la inquietud de mi alma.

Como debes suponer, yo no podría continuar mucho tiempo en una condición así;
naturalmente se buscaría alivio de alguna manera.
El cruel y sutil estaba cerca, y me eran presentados pensamientos como:
"`He engañado a mi alma imaginándome ser objeto de la misericordia divina,
y atribuyéndole mis primeros sentimientos y esperanzas a la operación de la gracia.
Mi corazón y afectos todavía son terrenales y sensuales,
aunque por un tiempo mi imaginación haya felizmente
pintado un cuadro de un interior más celestial.
También he engañado a mis hermanos y al mundo al hacer profesión religiosa.
Así que, de ahora en adelante, viéndome en la verdadera luz,
debo mostrarme como realmente soy, y no continuar más como un lobo en piel de oveja.`"

Para una mente cansada y sin consuelo,
en la que la semilla de vida no estaba suficientemente arraigada
como para hacerme capaz de soportar la tribulación,
este cebo del enemigo fue infelizmente tragado.
Después de algunos meses de vadear profundamente, o más bien,
de sumergirme en aguas oscuras,
en una maligna hora cedí a la sugerencia de que "`el descanso era bueno`"^
footnote:[Génesis 49:15]
sin importar cómo se obtuviera.
La tierra de mi corazón que antes había visto como
un yermo de horrible soledad y valle de lágrimas,
ahora parecía más placentera y tranquila,
y así incliné de nuevo mi cuello al yugo del pecado
y me convertí en un esclavo de trabajos forzados.
Entonces la restricción religiosa fue en gran medida dejada de lado,
aunque por un tiempo me mantuve dentro de los límites de la moralidad,
y mantuve el orden que era común en la casa de mi padre,
yendo con mi familia los primeros días de la semana al lugar de su adoración,
llamado la iglesia, y oyendo a algunos de ellos leer las Escrituras.
Pero ¡ay!,
estos límites pronto se volvieron dolorosamente estrechos para mi voluntad egoísta,
y para los dictados de mis propensiones naturales.
Y cuando me separé del único poder que me refrenaba,
ellas despertaron con fuerza en mi corazón esclavizado y tomaron las riendas gradualmente,
de modo que fui realmente llevado cautivo a la voluntad del cruel tentador de la humanidad.
Con el tiempo, no quedaba en mí ningún deseo de resistir la tentación,
sino que cada nuevo camino que abría algo agradable ante mi vista,
era perseguido ávidamente.
Iba a las tabernas y el juego (el principal placer ahí) se volvió particularmente atractivo,
de modo que noches enteras fueron dedicadas a ese vicio destructivo.
En resumen, por triste que sea contarlo, me convertí en un completo libertino,
y mi postrer estado fue mucho peor entonces que el primero.

Antes de seguir relatando las consecuencias de mi vil apostasía,
puede que sea mejor retroceder un poco al sombrío estado y a los ejercicios que la precedieron,
con el fin de dar una visión clara de lo que realmente tomó lugar.
Como ya he dicho, mi primera resolución de dedicarme al Todopoderoso Dios fue sincera.
Realmente intenté buscar mi porción únicamente en Él,
a partir de ese día. Pero mis votos fueron hechos apresuradamente,
sin considerar (y de hecho sin saber) el costo del discipulado.
También me hallaba en un estado considerable de ignorancia con respecto a mí mismo,
particularmente en lo que se refiere a mi inestabilidad de espíritu,
mi aterrada mente que rehuía el sufrimiento,
y mi tenacidad en la búsqueda de los deleites presentes,
cualquiera que fuera el objeto que tuviera a la vista.
La humildad,
el principal requisito para colocar un fundamento seguro
para la estabilidad y verdadero avance espiritual,
fue poco considerada.
Se deseaban y esperaban grandes cosas desde el principio,
y la emoción humana era apreciada como una señal del verdadero celo,
y se pensó erróneamente que era un característica de la imagen renovada y pura.

Por lo tanto, cuando fui llevado a mirar hacia dentro,
y llegué a conocerme más íntimamente;
cuando llegué a algún discernimiento con respecto a la diferencia
entre la pasión de la criatura y la luz divina;
y cuando se me hizo sentir el poder de convicción de dicha luz,
y ver en ella que mi condición estaba muy por debajo
de lo que yo había pensado que estaba,
entonces se levantó de la parte carnal una gran angustia,
que al ganar gradualmente terreno, le dio al enemigo una ventaja,
y al final un triunfo sobre mí. Al no tener el amor al yo nada de qué alimentarse,
pronto se cansó de la privación, y se vio agobiado bajo un ayuno tan humillante.
El retiro para las devociones privadas--tras haber sido despojado de todo lo
que al principio le había dado un sabor dulce--se volvió molesto para mí,
y las excusas para omitirlo eran fácilmente permitidas, si no buscadas.
Recuerdo muy bien una de las excusas, a saber,
comencé a conversar sobre temas religiosos durante
el tiempo que antes dedicaba a la devoción privada.
Pero pronto aparecieron convicciones contra ello,
y vi que recurría a las conversaciones para aliviar
el peso de mi apropiado ejercicio y carga.
Esto trajo condenación y un incremento de desánimo,
y mi confianza naturalmente disminuyó. Pronto siguieron actos de
rebelión contra las claras convicciones sobre otras cosas,
hasta que finalmente, abandoné por completo mi esperanza.
Los cielos eran como bronce sobre mi cabeza,
y al no tener expectativas de que alguna oración mía fuera capaz de atravesarlos,
produjo por último los efectos ya aludidos.
Puedes ver así, amigo mío, que hubo un "`retroceso`"^
footnote:[Hebreos 10:38-39]
a la hora de la tribulación, en lugar de haber "`guardado la palabra de paciencia.`"^
footnote:[Apocalipsis 3:10]
En efecto, el amor divino me había atraído y llevado al desierto,
al valle de Acor (es decir, de la aflicción), que en Su sabiduría,
era el lugar asignado para que yo habitara por un tiempo.
Si yo hubiera continuado ahí,
hasta que todo lo que estorbaba mi progreso hacia la victoria sobre los enemigos de
mi alma hubiera muerto su muerte señalada--esperando y tranquilamente aguardando la
salvación del Señor--no tengo dudas de que habría sido dadas viñas desde ahí^
footnote:[Oseas 2:14-15]
y habría cantado de la salvación del Señor,
la que Él de seguro puede dar al verdaderamente humilde y pobre en espíritu,
incluso en la estación nocturna.

Pero, ¡doloroso de contar!, entonces me convertí en esclavo de mis propensiones naturales.
Incapaz de soportar la reflexiones sobre mí mismo,
busqué anhelosa y continuamente compañía,
y usé todos los medios para silenciar la voz de la consciencia,
que a veces seguía siendo terriblemente fuerte.
Porque aunque yo de esa manera buscaba huir de la
presencia del Señor del cielo y de la tierra,
aun así, tal era Su piedad y misericordia para con mi pobre alma,
que no me abandonó del todo.
En lo secreto de mi corazón,
yo todavía era atravesado por las flechas de Su luz condenatoria,
y oprimido por un terrible temor a la muerte y al juicio por venir.
Sin embargo,
durante doce años busqué alivio sumergiéndome más
y más profundamente en las actividades libertinas;
de modo que cortejé incluso aquellos vicios a los que no tenía inclinación particular;
y (si existe tal cosa) tenté al tentador,
y de hecho me convertí en su "`legítimo cautivo.`"^
footnote:[Isaías 49:24 RV1602P]
¡Oh! ¿Hay alguna condición más repleta de horror y tinieblas internas que la de un apóstata?

En el transcurso de esta larga noche de apostasía,
ocurrieron algunos eventos significativos.
Me casé y tuve varios hijos.
También establecí una prometedora relación comercial,
con la que tenía buenas perspectivas de proveer para mi familia.
Pero al no estar suficientemente consciente del peso de
las solemnes obligaciones bajo las que estaba entonces,
el placer fue generalmente perseguido con avidez, particularmente el juego;
y los deberes del negocio y de la familia se hicieron cada vez más insípidos,
y fueron en gran medida descuidados.

Así continué--aparentemente despreocupado y feliz,
pero en realidad miserable--hasta el año 1789, el año treinta y seis de mi vida,
cuando le plació a mi sufrido y misericordioso Dios visitarme con una severa enfermedad.
Totalmente limitado por ésta,
fui abandonado entonces a mis propios pensamientos y reflexiones sobre mi camino pasado,
y se me hizo sentir terriblemente el estado al que me había llevado; es decir,
"`sin esperanza y sin Dios en el mundo.`"^
footnote:[Efesios 2:12]
Yo sabía que "`quebranto y desventura hay en sus caminos,`"^
footnote:[Romanos 3:16]
y pronto fui convencido de que no había esperanza de encontrar
el camino de paz a menos que me volviera con todo propósito de
corazón hacia Aquel contra quien me había rebelado tan profundamente.
Yo sabía que una reforma parcial era odiosa ante los ojos de mi omnisciente Creador,
especialmente por alguien como yo.
Regresaron todos mis puntos de vista anteriores con
respecto a una verdadera condición religiosa,
y a la profunda obra interna que era necesario atravesar con el fin de alcanzarla.
Vi el costo de un verdadero discipulado con un Maestro crucificado,
y la vista era aterradora para mi largamente corrompido y degradado espíritu.
La "`temida risa del mundo`" tampoco era algo insignificante a tomar en cuenta;
porque por ese tiempo,
yo era conocido por muchas personas de varias clases en la sociedad civil,
y a través de conexiones matrimoniales tenía amistad con
algunos que vivían con mucha grandeza en modales y propiedades.
A todo esto se sumó un fuerte temor a que mi inestabilidad natural prevaleciera siempre,
y que nunca alcanzara la fidelidad de espíritu.
La lucha fue profunda y dolorosa, pero al final,
se me concedió fuerza para renovar mi pacto con un Dios bueno y misericordioso,
que había esperado por mucho tiempo mi regreso,
y que ahora me llamaba fuertemente a exaltarlo de manera tal,
que me hiciera capaz de participar en Sus vivas misericordias
y en el tierno perdón de mis múltiples pecados.

Consecuentemente, el 26 del mes noveno de 1789,
ante los ojos del Dios que escudriña el corazón,
tomé la decisión de que a partir de ese momento, buscaría seriamente mi paz con Él,
rompería con todos mis malos hábitos, y entraría en un camino verdaderamente religioso;
pidiendo fervorosamente la fuerza para cumplir con mis votos, y no temiendo nada más,
sino la infidelidad o la disminución de mis fervientes deseos
que sentía entonces de regresar a la casa de mi Padre celestial.
El Señor misericordiosamente consideró mis peticiones.
Me liberó del horror que sentía ante el pensamiento de la muerte,
el cual había sentido profundamente y por largo tiempo en mi alma.
Así reuní un poco de fuerza, y mi cabeza a veces era levantada en esperanza.
A principios del año 1790, fui favorecido también con un regreso de la fuerza corporal,
de modo que los asuntos internos y externos parecían
más alegres que en muchos años anteriores.
Pero, ¡oh,
poco me imaginaba la nube que se estaba acumulando sobre mí y estaba
a punto de sumirme en las más profundas dificultades.

[.asterism]
'''

+++[+++Aquí nuestro querido amigo entra en detalles específicos
que no pueden ser expuestos ante el público con propiedad.
Baste decir,
que la nube que se cernía estalló sobre él. Su tranquilidad doméstica
fue quebrantada por varias circunstancias muy dolorosas,
sumado a lo cual (por la repentina muerte de su padre en esa misma época,
y algunas muy inesperadas consecuencias que le sobrevinieron)
sus negocios se vieron tan seriamente afectados,
que a pesar de que continuó durante varios años,
finalmente se vio en la necesidad de abandonar completamente su negocio,
con la pérdida de casi todo lo que era de su propiedad,
y recurrir al empleo de un contador para su subsistencia.
Pero aquellos que lo conocieron en esa época,
pueden dar testimonio de su conducta cristiana durante esos eventos profundamente difíciles.
Y hay buenas razones para creer, que por su paciencia y rendición bajo ellos,
éstos se convirtieron en una bendición para él.]

[.asterism]
'''

En lo que me sucedió externamente, creo que se verificó que, tarde o temprano,
al descarriado de corazón se le hace comer el fruto de sus propios caminos,
y que muchos azotes están preparados para aquellos que,
conociendo la voluntad de su Maestro, se rebelan contra ella.^
footnote:[Lucas 12:47]
Paso ahora al relato de los ejercicios y convicciones que me llevaron
a unirme al pueblo con el que ahora tengo comunión religiosa.

Mis convicciones con respecto a la religión y adoración al Todopoderoso Dios,
siguieron siendo las mismas que tenía en los primeros días, y consecuentemente,
los principios y prácticas de cada sociedad de Cristianos
eran bastante diferentes de mis sentimientos,
excepto los de los Amigos.
Sin embargo,
creyendo que la división de la iglesia en sectas es producto
de un alejamiento del Espíritu puro de Cristo,
por un tiempo cuestioné fuertemente si era apropiado
que me uniera a alguna de ellas exclusivamente;
y así, decidí buscar a Dios en secreto para que me guiara en este asunto,
asistiendo ocasionalmente a las diferentes asambleas,
pero mayormente a las de los Amigos y Metodistas.
Es probable que a muchos esta conducta les haya parecido el efecto de un juicio no resuelto,
pero ese no era exactamente el caso.
Porque me mantuve sobre el fundamento antes mencionado,
creyendo todavía en la necesidad del santo poder vivificador de Dios,
para revivir en el hombre la imagen santa perdida en la que fue creado al principio,
y que Jesucristo era ese poder internamente revelado en el hombre.
Por consiguiente, buscar ayuda en cualquier cosa que no fuera esto,
me parecía aferrarme a algo fundado sobre ese pacto "`que no puede hacer perfecto`"^
footnote:[Hebreos 9:9]
a nadie,
porque se basaba en prácticas externas que no podían
hacer nada eficaz en lo que a la consciencia se refiere.
Por lo tanto, el bautismo que verdaderamente salva (en mi opinión),
es la unión al Espíritu de Jesucristo que renuncia y da
la victoria sobre el pecado y el mundo en el tiempo presente,
tal como dice el apóstol: "`Porque todos los que habéis sido bautizados en Cristo,
de Cristo estáis revestidos.`"^
footnote:[Gálatas 3:27]
"`Pero los que son de Cristo han crucificado la carne con sus pasiones y deseos.`"^
footnote:[Gálatas 5:24]
Esto lo tomé como el verdadero bautismo espiritual.

La llamada cena del Señor que Cristo mismo ordenó,
era ciertamente comer "`Su cuerpo`" y "`beber Su sangre,`"^
footnote:[Juan 6:53]
(pues como dice Pablo en otra parte, "`hay cuerpo espiritual`"^
footnote:[1 Corintios 15:44]). Pero aquí también,
todos los actos externos parecen insignificantes,
viendo que Cristo declaró que participar de Su carne y sangre es unirse
a Él en la misma naturaleza que Él está unido a Su Padre celestial:
"`El que come mi carne y bebe mi sangre, en mí permanece,
y yo en él. Como me envió el Padre viviente, y yo vivo por el Padre,
asimismo el que me come, él también vivirá por mí.`"^
footnote:[Juan 6:56-57]
Ahora, si esto es lo que significa esta unión viva, ¿podemos suponer entonces,
que al participar Cristo de la Pascua con Sus apóstoles,
tenía la intención de ordenar la práctica de alguna nueva señal externa y visible,
en lugar de esto?
Como Sumo Sacerdote "`según el poder de una vida indestructible,`"^
footnote:[Hebreos 7:16]
¿ministraría Él a Su iglesia de la misma manera que lo hacían los sacerdotes bajo la ley,
cuyos ofrendas y sacrificios, como leemos, "`no pueden hacer perfecto,
en cuanto a la conciencia, al que practica ese culto,
ya que consiste solo de comidas y bebidas, de diversas abluciones,
y ordenanzas acerca de la carne, impuestas hasta el tiempo de reformar las cosas`"^
footnote:[Hebreos 9:9-10]? Según Lucas, las palabras de Cristo fueron:
"`Haced esto en memoria de mí;`" pero ni Mateo ni Juan, que estaban presentes,
tomaron nota de esta instrucción. ¿Podrían haber omitido la mención de esto,
si ellos la hubieran considerado una ley obligatoria
sobre la iglesia según su significado literal,
o una nueva institución establecida por el Señor mismo para
ser practicada tan solemnemente como lo había sido la Pascua?
No creo que esto sea en absoluto probable.
Parece más bien, que tanto el mandato como la declaración: "`Este es mi cuerpo,
etc.,`" tenían la intención de trasmitir algo más espiritual en naturaleza
que un mero acto externo que cualquier hombre no regenerado podría realizar;
es decir, aquello que el apóstol Pablo aludió cuando dijo: "`Limpiaos, pues,
de la vieja levadura, para que seáis nueva masa, sin levadura como sois;
porque nuestra pascua, que es Cristo, ya fue sacrificada por nosotros.
Así que celebremos la fiesta, no con la vieja levadura,
ni con la levadura de malicia y de maldad, sino con panes sin levadura,
de sinceridad y de verdad.`"^
footnote:[1 Corintios 5:7-8]

Ahora, es indudablemente cierto que los primeros convertidos celebraban sus "`ágapes`"^
footnote:[Judas 1:12]
en conmemoración del partimiento externo del pan que hizo nuestro
Señor (en la que tenían la aprobación de los Apóstoles mismos).
Pero ¿no podemos razonablemente concluir que esta,
así como también en muchas otras prácticas externas,
ellos las concedieron por el estado débil de sus hermanos
y el fuerte apego que tenían a los ritos mosaicos?
Que lo hicieron así en algunos asuntos en particular (como la circuncisión) es muy evidente.
Y en cuanto a las observaciones del apóstol Pablo a la iglesia de Corinto,
con respecto a los abusos que habían prevalecido en la manera de celebrar esos ágapes,
nada en estos pasajes parece indicar una institución permanente,
ni las palabras del apóstol parecen estar dirigidas a un
estado muy maduro en la vida espiritual--porque dice:
"`No pude hablaros como a espirituales, sino como a carnales, como a niños en Cristo.`"^
footnote:[1 Corintios 3:1]

Con respecto a algunos otros puntos cardinales en lo que la Sociedad de
Amigos difiere de la mayoría de los demás cuerpos de Cristianos--a saber,
los de la guerra,
los juramentos y la naturaleza del verdadero ministerio evangélico--tuve la oportunidad
de manifestar públicamente mi unión a estas cosas mucho antes de convertirme en miembro,
o de saber que lo sería. La sencillez y simplicidad en la vestimenta,
en los modales y en el hablar me parecían, desde mis más tempranas convicciones,
estar muy en consonancia con los preceptos y ejemplos de nuestro Santo Redentor;
y yo sabía bien que la vanidad de mi propio corazón era
lo que me inducía a conformarme al mundo en estos aspectos.
Por tanto, la práctica de negar el yo en estas cosas parecía apropiada y necesaria.
Y aquí me viene a la mente decir algo sobre la amplia
desviación de la simplicidad que es en Cristo,
y de la guía de Su manso, amoroso y Santo Espíritu,
que es actualmente tan evidente en la iglesia externa y visible; de modo que, en general,
se permite e incluso se defiende,
una total indiferencia tanto de la letra
como del espíritu del Evangelio de Cristo con respecto a estos puntos.

Muchos ridiculizan nuestra atención a la manera de vestir como algo irrelevante
para nuestra conducta delante del Todopoderoso Dios,
o para nuestro caminar delante de Él en humildad, justicia y santidad.
Sin embargo,
es un tema que uno de los santos profetas vinculó
con la profunda rebelión de Israel contra su Creador,
declarando los inminentes juicios de Dios por este motivo, (ver Isaías 3:18-24). Otro,
entre los hijos de sabiduría de antaño, declara: "`El atuendo del hombre,
la risa de sus dientes, su caminar revelan lo que es.`"^
footnote:[Eclesiástico 19:30]
Y si le sumamos a esto los claros y positivos mandatos de los apóstoles Pablo y Pedro,^
footnote:[1 Pedro 3:3; 1 Timoteo 2:9]
que tan expresamente prohíben la atención al adorno de la persona en lo que viste,
como el octavo mandamiento prohíbe incrementar la riqueza
mediante el fraude en cualquier cosa que se haga,
¿no debemos ver claramente que un seguidor de Cristo es llamado a dar, por su ejemplo,
un testimonio completo contra la conformación al espíritu del mundo?
¿Y no es aparente que el espíritu de este mundo persigue,
a través de la moda en el vestir,
una importancia y honor en la apariencia que van más allá
de lo que requieren nuestras necesidades corporales?

Respecto a la sencillez del lenguaje, te he dicho que, hasta cierto punto,
su propiedad coincidía con mi juicio previo.
Así era,
pero pasó algún tiempo antes de que yo sintiera la necesidad
de adoptarlo tan plenamente como lo hacen los Amigos.^
footnote:[Aquí William Lewis habla específicamente sobre la manera
en que el idioma inglés estaba siendo corrompido en aquel momento,
al dirigirse a personas individuales con pronombres en plural
para mostrar parcialidad o adulación. Sin embargo,
el principio de honrar al Señor con "`cada palabra
que sale de nuestra boca`" (Efesios 4:29;
Santiago 3:2-12) es atemporal,
y el Espíritu de Verdad aplicará esto en los corazones de cada verdadero discípulo,
independientemente del idioma y la cultura.]
Lo que me llevó a una consideración más cercana y profunda con respecto
al motivo por el que ellos creen correcto diferir de otros en este sentido,
según recuerdo,
fue algo así. Después de dos años de retiro de todos los lugares públicos
de adoración (excepto cuando era particularmente invitado a alguno),
en mis horas de recogimiento privado, que entonces eran muchos y diarios,
llegó forzosamente a mi vista que un camino tan solitario o recluido
no estaba en concordancia ni con el espíritu del evangelio,
ni con los claros mandatos de los apóstoles,
ni con la práctica de los creyentes de ninguna época de la iglesia.
Vi que la unión y comunión fraternal era la esencia misma del espíritu del evangelio,
que respira buena voluntad para con todos, ama sin fingimiento,
que genuinamente se preocupa por el bienestar espiritual de los demás,
y soporta sus cargas.
Al abrir más mi mente a estas consideraciones, pronto presionaron pesadamente sobre mí,
y mis pensamientos se volcaron con deseos en pos de comunión religiosa.
En mi primera mirada en esa dirección,
la Sociedad de Amigos parecía ser la única a la que podía unirme,
pero parecía apropiado que mi juicio y mi práctica estuvieran
primero completamente de acuerdo con los de ellos;
y a excepción del lenguaje, ya casi lo estaban.
Pero la sola idea de un cambio en este sentido causó
tal retroceso y tal sensación de pavor,
que me indujo a intentar cernir sus argumentos y probar que carecían de fundamento.
No recuerdo cuánto traté de evadir la fuerza de lo que ellos decían sobre este tema,
sólo que en última instancia,
se recurrió exclusivamente a una búsqueda diligente en las Escrituras sobre este asunto.

Desde aproximadamente ese tiempo (1793),
comencé a tener una firme aprensión de que no alcanzaría los requerimientos divinos,
si no me sometía a la cruz en relación con el lenguaje.
No obstante, continué retrocediendo y luchando por casi dos años,
durante los cuales fueron presentadas muchas oraciones (con
lágrimas) al bondadoso Dios pidiéndole guía en este asunto,
y fuerza para soportar todo lo que Él viera adecuado imponer
sobre mí para la reducción de mi voluntad natural,
y la humillación de mi alma delante de Él. Finalmente, con mucha inquietud de espíritu,
me sometí a adoptar lo que los Amigos llaman "`lenguaje sencillo,`" con lo cual,
otra piedra de tropiezo fue removida de mi camino.

A partir de ese momento (el año 1795) asistí a sus reuniones regularmente,
y unos tres años después, al solicitar ser admitido como miembro de las Sociedad,
fui recibido como tal en la reunión mensual de mi ciudad natal.

[.signed-section-signature]
William Lewis

[.asterism]
'''

El relato anterior de la vida y experiencia religiosa de
William Lewis fue escrito por él mismo en el año 1797,
en cumplimiento de una ferviente solicitud de un amigo cercano.
Dicho relato le fue dado a este individuo con la orden estricta de que no fuera publicado,
y ni siquiera copiado para uso privado, durante la vida del autor.
No cabe duda,
que habiendo experimentado de primera mano que el
corazón es "`engañoso más que todas las cosas,
y perverso,`" e inclinado a la apostasía,
no estaba dispuesto a traer crítica sobre la Verdad al publicar su testimonio,
antes de saber con certeza que había resistido hasta el final.
No obstante, vivió diecinueve años más después de haberlo escrito,
y continuó siendo un fiel seguidor de Cristo, un miembro muy útil,
y eventualmente ministro de la Sociedad de Amigos, hasta su fallecimiento en 1816.
En el año 1819, se reunió y publicó una colección de sus cartas,
a partir de las cuales se extraen los siguientes dos ejemplos.

[.asterism]
'''

[.letter-heading]
Para un Joven Religiosamente Dispuesto

[.salutation]
Querido Amigo,

El interés despertado en mi mente durante las conversaciones
personales que hemos sostenido antes,
relacionadas con tu bienestar eterno,
se enciende ahora con más fuerza de la usual al enterarme de tus presentes circunstancias;
y bajo el sentimiento de ello, en amor fraternal tomo mi pluma.

Mi corazón se alegra en la esperanza que siente por
tu apertura a las manifestaciones de la luz divina,
y a rendir plena obediencia a todos sus mandamientos,
en el gradual despliegue de la buena,
agradable y perfecta voluntad de tu Padre celestial, con respecto a ti.
Esta esperanza, digo, brota en mí,
al ver que ya has contemplado la necesidad de no conformarte más al presente siglo malo,
tanto en sus pompas y vanidades,
como en sus formas supersticiosas en las cosas espirituales,
con el fin de experimentar la renovación de la mente que debe ser experimentada,
antes de que nosotros podamos distinguir claramente la voz
del buen Pastor de la del extraño. Ya has visto esto,
y has tomado la bendita resolución de no consultar más con carne y sangre,
al rendir obediencia a la visión celestial, y por causa de Cristo,
atreverte a ser estimado un tonto por el sabio de este mundo.
Ahora, queda para ti '`reconocerlo __en todos tus caminos__`'^
footnote:[Proverbios 3:6]
en la medida que Él te atraiga hacia Sí;
y no desanimarte si el camino que se abre delante de ti parece duro,
y ves a pocos viajando por él. Confía en la promesa: "`Hierro y bronce será tu calzado,
y como tus días, así será tu fortaleza.`"^
footnote:[Deuteronomio 33:25]

Me parece que el presente es el tiempo de la más misericordiosa
visitación para ti--un día que el Señor ha hecho,
en el que Él ha pasado y mirado sobre ti, y dulcemente se ha revelado a ti.
¡Ojalá devuelvas amor por amor, mientras este día de poder continúa,
ya que sólo en él se forja en nuestras almas la disposición de hacer pacto con el Señor,
mediante los sacrificios que Él requiera!
Para un corazón plenamente rendido a esta divina atracción,
nada parecerá demasiado querido como para no desprenderse de ello,
ni nada se verá demasiado doloroso de soportar,
por causa de Aquel que nos ha comprado al precio de Su propia sangre preciosa.
Está escrito:
"`Porque fuerte es como la muerte el amor...las muchas aguas no podrán apagar el amor,
ni lo ahogarán los ríos;`"^
footnote:[Cantares 8:6-7]
pero esa muerte que ha pasado a todos los hombres,
siempre será hallada como un poder que nada sino el amor puede destronar;
y de este poder de muerte fluyen tales aguas,
que sí pueden apagar y ahogar todos los fuegos hechos por
el hombre y el celo de las criaturas en todas las formas.

Ahora, pues, querido amigo,
es tu tiempo de '`levantarte y sacudirte del polvo de la
tierra,`' y de '`soltar las ataduras de tu cuello,`'^
footnote:[Isaías 52:2]
y seguir adelante para conocer al libertador de Sion.
Ahora es tu tiempo de '`atar el sacrificio con cuerdas a los cuernos del altar,`'^
footnote:[Salmos 118:27]
y aspirar tras una parte y herencia con los que han oído y obedecido el llamado:
"`Juntadme mis santos; los que hicieron conmigo pacto con sacrificio.`"^
footnote:[Salmos 50:5]
¡Oh,
yo creo que si los llamados del Señor en este día
le entregaran sin reservas sus corazones a Él,
y en sencillez _confiaran en Su poder vivo dentro de ellos,_
pronto llegarían a ser más sabios que sus maestros,
y la luz de Su Palabra viva y eficaz resplandecería con un brillo que
eclipsaría mucho de lo que ahora es llamado (por muchos) brillo del evangelio!
Pero por desgracia, se escucha más el grito: "`Helo aquí,
o helo allí;`" que la voz interior que los llamó primero.
Y cuando su "`primer amor`"^
footnote:[Apocalipsis 2:4]
(que antes fue sentido en su preciosa influencia) empieza a disminuir,
con demasiada frecuencia la mente se instala en la teología sistemática,
con varias prácticas y ordenanzas de invención humana--un reposo
muy inferior del que está preparado para los hijos de Dios.

En vista de estas cosas,
es de gran consuelo para mí que estés dispuesto a abrir
paso en tu corazón para recibir la verdad del evangelio,
sin la mezcla de los conceptos de la criatura,
y habiendo visto que "`el Espíritu es el que da vida;
la carne para nada aprovecha,`" has tomado la sabia decisión
de esperar y oír al "`que amonesta desde los cielos,`"^
footnote:[Hebreos 12:25]
cuya Palabra es con poder y es (como Él mismo declaró) "`Espíritu y Vida.`"^
footnote:[Juan 6:63]
En efecto, esto me produce una gran satisfacción,
habiendo estado convencido por largo tiempo más allá de toda duda,
que nada menor que este poder vivo puede desalojar a Satanás de nuestros corazones,
o despojar al mundo y a la carne de su dominio sobre nuestros afectos y deseos.
Y habiendo sido así enseñado en adorable misericordia
a avanzar un poco en este camino nuevo y vivo,
y viendo que la Verdad misma ha declarado que no hay otro camino al Padre,
no es de extrañar entonces que repose sobre mí una preocupación
de recomendarlo encarecidamente a todos mis semejantes,
especialmente a los que están emprendiendo su viaje celestial.

Retén pues, sin vacilar, lo que tienes de esta fe, te lo ruego;
y en sencillez de corazón ríndete a sus operaciones.
Pon oídos sordos a los argumentos triviales a favor
de los sistemas actuales y modos externos de religión,
y más bien evita discutir mucho sobre ellos.
Mediante un vuelco interno real y constante de tu corazón hacia Dios,
encontrarás una renovación e incremento de esa fuerza que
te permitirá dejar que tu luz brille delante de los hombres,
de tal manera que dé indudable evidencia de su origen,
y de ese modo convencer a los opositores más poderosamente que por argumentos.
Al acostumbrarte así a buscar continuamente acceso a tu Padre celestial,
estarás cada vez más convencido de la vanidad de
las búsquedas mundanas y deleites de la criatura,
y un verdadero gusto por las cosas espirituales se
levantará por encima de todas las "`vanidades ilusorias.`"^
footnote:[Jonás 2:8]
Encontrarás también tu mente ensanchada,
y los misterios del reino de Dios abiertos por Aquel que
tiene "`la llave de David`" en Su posesión. Esfuérzate,
entonces, mi querido amigo,
por retirarte y volverte de los objetos terrenales (tanto
como los deberes de tu vocación externa te lo permitan),
buscando siempre ese pan que desciende de Dios desde los cielos.
Y no dejes que tus recreaciones permitidas sean tales que tengan
alguna tendencia a atenuar tus aspiraciones en pos de Dios;
manteniendo en mente la declaración del apóstol: "`El que dice que permanece en él,
debe andar como él anduvo.`"^
footnote:[1 Juan 2:6]

Al tomar la decisión de usar una vestimenta sobria y adoptar modales sencillos,
confío en que has seguido a tu Guía espiritual,
y que no has corrido delante de Él. Verdaderamente me sorprende
que personas espiritualmente despiertas de todas las denominaciones,
no vean la necesidad de dar un testimonio fiel contra las
manifestaciones de orgullo y vanidad en estas cosas.
Si alguno piensa entonces que es extraño que te salgas del camino común en este aspecto,
se le puede responder con el lenguaje de David: "`¿Acaso no hay una causa?`"
^
footnote:[1 Samuel 17:29 RVG]

Aunque he dicho mucho,
hay todavía un asunto sobre el cual no me siento completamente tranquilo de callar,
y es la necesidad de "`calcular los costos`"^
footnote:[Lucas 14:28]--ese costo al que todo verdadero discípulo de un
Señor crucificado debe someterse para obtener la perla de gran precio.
En realidad, es necesario entender plenamente la declaración del apóstol:
"`Es necesario que a través de muchas tribulaciones entremos en el reino de Dios.`"^
footnote:[Hechos 14:22]
Partiendo con esto en mente,
estarás en cierto grado armado contra los asaltos y tentaciones de nuestro cruel enemigo.
Porque cuando la capacidad de sentir el favor divino,
en sabiduría es retirado de aquellos que han comenzado su viaje en la luz,
y cuando las tinieblas que permanecen entonces llegan a ser más manifiestas,
el enemigo con frecuencia tienta al alma con la sugerencia de que todo
lo anteriormente disfrutado y creído era una imaginación engañosa.
En esos momentos, cuando la fuerza del mal se siente profundamente,
hay una disposición en los humildes a escuchar demasiado la voz del enemigo,
y a permitir la pregunta burlona: "`¿Dónde está tu Dios ahora?`"--en lugar de,
con fe desnuda, abrazar el alentador lenguaje del profeta:
"`¿Quién hay entre vosotros que teme a Jehová, y oye la voz de su siervo?
El que anda en tinieblas y carece de luz, confíe en el nombre de Jehová,
y apóyese en su Dios.`"^
footnote:[Isaías 50:10]
No obstante, creo firmemente que el alma verdaderamente devota,
que sinceramente ha colocado su corazón en seguir al Cordero dondequiera que vaya,
será capaz de soportar esa hora y ese poder de las tinieblas,
y el amor de su sufriente Salvador producirá la disposición
de ir con Él al otro lado del Arroyo de Cedrón,
y tomar su porción asignada de esa copa, que al tomarla,
causó que Él sudara grandes gotas de sangre.
Y al ser fortalecida así por el Todopoderoso Redentor y Preservador de
los hombres en cualquier prueba que Él considere adecuada dispensar,
que sea pronunciado este lenguaje en humilde rendición: "`No se haga mi voluntad,
sino la tuya.`"

Este último comentario podría parecerles a algunos inoportuno y desalentador; para mí,
sin embargo, me parece seguro.
No debemos creernos más sabios que el gran y compasivo
Maestro que conocía bien la timidez de Sus pequeños,
a quienes, mientras estaban todavía en estado de infancia,
les dijo claramente que toda pretensión al discipulado era vana a menos
que hubiera una disposición a negar al yo y tomar la cruz cada día. Nunca
me he sentido unido a cierta forma de sabiduría carnal que,
al tratar de enlistar soldados bajo el estandarte de Cristo,
se esfuerza por seducir con gratificaciones temporales,
mientras mantiene fuera de la vista la dureza que debe ser soportada.
Y ahora, mi querido amigo, concluyo encomendándote a Dios y a la Palabra de Su gracia,
que tiene poder para edificarte.
Que seas favorecido para crecer en la fortaleza del Señor y en el poder de Su fuerza,
para que puedas resistir en el día malo, y habiendo acabo todo, estés firme.

[.signed-section-closing]
Me despido afectuosamente,

[.signed-section-signature]
William Lewis

[.asterism]
'''

[.letter-heading]
A un Joven Miembro de la Iglesia de Inglaterra

[.salutation]
Amado amigo,

En un temprano periodo de tu vida,
mi pluma fue usada para comunicarte algo de ese amor que abarca en toda su amplitud,
toda la creación inteligente de Dios,
y que (al ser puro en naturaleza y origen) busca gloria y virtud para todos;
dirigiéndolos a tal santidad de corazón y vida,
que los capacite para la unión y comunión con la Fuente de todo bien.

Ni el paso del tiempo, ni la falta de interacción personal,
han borrado mis primeras impresiones con respecto a ti.
Todavía recuerdo las respiraciones de tu espíritu hacia el Dios de tu vida,
en un tiempo cuando te llevaban a considerar la brevedad e incertidumbre del tiempo,
y la espantosa condición de aquellos que, en sus lechos de muerte,
sienten su carencia de Cristo.
Entonces, se levantó en ti una viva preocupación por incrementar tu talento,
y dedicar tu tiempo al bendito propósito de buscar, mediante la oración en tu armario,
comunión con el Amado de las almas.
Recuerdo muy bien, que cuando mirabas a Jesús,
eras capaz de ver la necesidad de un vuelco más frecuente
y sincero hacia Él en esta forma,
y de renunciar a las tontas diversiones en las que las personas
pasan la mayor parte de sus preciosas horas.
Cediendo así a la dulce atracción del amor eterno,
fuiste llevado en el seno del tierno pastor de Israel, y gustando tú mismo Su bondad,
manifestaste a otros que '`de la boca de los niños y de los que maman,
Él (todavía) ordena la alabanza,`' testificando a todos
los presentes que '`debemos considerar este mundo,
como dado a nosotros meramente para prepararnos para el siguiente.`'

Todo esto que digo, querido amigo, lo tengo ahora presente y fresco en mi mente.
Tenme paciencia, si bajo esta impresión,
te sugiero el peligro que corremos todos de apartarnos del ferviente y casto "`amor
de nuestro desposado,`" a menos que mantengamos el más decidido propósito de corazón,
fortalecido por la vigilancia diaria y la ferviente oración
a Aquel que es el único capaz de guardarnos de caer.
El peligro está por todos lados,
y continúa a través de varias etapas de nuestro viaje y lucha cristianos,
a partir de las fuerzas combinadas de las seducciones de
este mundo y de los deseos de nuestra naturaleza caída.

Entonces,
si después de dar pasos en el "`camino a Sion`" y haber
alcanzado cierto conocimiento (por experiencia viva),
tanto de la bondad del Señor como de nuestra propia debilidad y depravación; si todavía,
por la traición de nuestros propios espíritus estamos todos en continuo peligro de caer,
¿cuánto más puede el astuto tentador de las almas apartar la mente joven e inexperta?
Porque los jóvenes son particularmente acosados por deseos internos y tentaciones externas,
y si no hay un esfuerzo constante por huir de ambos,^
footnote:[2 Timoteo 2:22; 1 Pedro 2:11]
éstos librarán tal guerra contra el alma,
que poco a poco irán derribando todas sus fuerzas,
y le robarán y arruinarán su paz con Dios.
En esta etapa de tu vida en la que ahora me dirijo a ti en el amor de mi espíritu,
y sabiendo también que hay muchos peligros que son únicos para tu presente situación,
no puedo evitar sentir una gran preocupación por ti,
no sea que los primeros brotes verdes de la planta de justicia
en tu alma inhalen el aliento infeccioso del espíritu del mundo,
y sean cortados antes de que las flores se abran completamente.
O, cambiando de metáfora, que por abandonar la luz pura de Jesucristo,
"`tu plata se convierta en escoria`" y "`tu vino se mezcle con agua.`"^
footnote:[Isaías 1:22]
Nada, amigo mío,
puede preservarte de esto sino un ojo puro que sólo
busque la gloria de Dios en todos tus pensamientos,
deseos y propósitos, y una total dependencia de la gracia vivificadora,
limpiadora e iluminadora que está en Cristo Jesús. Sin esta gracia,
no podemos hacer nada que pueda encender o mantener viva una chispa de la vida celestial,
o lavar la mancha del pecado de nuestras almas inmortales.
Sin este ojo puro, el corazón siempre está dividido y es inestable,
nuestra fidelidad es como la nube de la mañana que se va,
y no tendremos capacidad de recibir ese brillo que
hace que '`todo tu cuerpo esté lleno de luz.`'^
footnote:[Mateo 6:22-23]

¡Oh, este poder de Dios que verdaderamente hace que Jesús sea Señor en nosotros,
y "`sabiduría, justificación, santificación y redención`"^
footnote:[1 Corintios 1:30]! ¡Qué error esperar ayuda de algo que no sea esto!
Porque viendo que la necesidad de tener un Salvador radica en nuestra profunda
caída de la imagen santa de Dios en la que Él creó al hombre en el principio,
a la vida terrenal y sensual; y viendo además,
que nada puede efectuar un cambio real en nuestro estado sino el mismo
poder que le dio vida a todos los espíritus inteligentes al principio;
es, por lo tanto,
vano e ineficaz esperar que la obra de redención provenga de otro
nombre (o poder) bajo el cielo que no sea el de Cristo--la Palabra
viva por la que todas las cosas fueron creadas al principio.
Así, pues, en toda nuestra búsqueda de Dios,
busquémoslo como un Espíritu vivificante del cielo,
el Único que puede levantar nuestro hombre interior a un lugar o estado celestial;
y el Único, que después de haberlo levantado, puede guardarlo de caer de nuevo.
Busquémoslo como una semilla de la naturaleza divina,
como un reino o manifestación de Dios dentro de nosotros, '`para que si en alguna manera,
palpando, podamos hallarle,`'^
footnote:[Hechos 17:27]
y encontrar que es, de hecho: "`Emanuel, Dios con nosotros.`"^
footnote:[Mateo 1:23]
Confío en que no te estoy hablando en una lengua completamente desconocida; sino que,
por tu lectura atenta de las Sagradas Escrituras,
con un entendimiento considerablemente iluminado,
y un corazón abierto para recibir la verdad como está en Jesús,
estés convencido de que lo que se perdió en el primer Adán,
y de que lo que el Señor del cielo, el Espíritu vivificante, revive en el hombre,
es un estado de vida, es decir,
la vida divina que es conforme a la imagen de Aquel que lo creó al principio.^
footnote:[Colosenses 3:10]

Cuando finalmente se conoce y se siente que __la vida__--la vida de
Dios--es de lo que nos hemos alejado y estamos muertos,
¡cuántas otras cosas se reducen a la insignificancia!
¡Cuán débil y vana parece la menor confianza en opiniones,
credos, modos de adoración, y particularmente, en las habilidades naturales humanas,
por muy cultivadas que estén! Bajo esta convicción,
todo es considerado menos que nada y vanidad,
excepto la manifestación de esa vida que es la luz de los hombres,
que vivifica y consuela con palpable evidencia, que, en efecto,
está realmente en nosotros y nosotros en ella,
que estamos unidos a ella y que somos de un espíritu con nuestro Señor redentor,
"`escondidos con Cristo en Dios.`"^
footnote:[Colosenses 3:3]

Ahora, ¿qué es lo que prepara al corazón para recibir plenamente una doctrina como esta?
Nada menos que el hambre y la sed de justicia;
un anhelo sincero y ardiente por esa pureza de corazón que ya podemos disfrutar,
y en última instancia, ver a nuestro Dios.
Porque al buscar y esforzarse tras este estado,
el alma pronto es dolorosamente consciente de la insuficiencia,
no sólo de las prácticas externas, o de la ayuda del hombre,
sino también de sus propios esfuerzos (por muy sinceros
y vehementes) por efectuar un cambio real,
o de poner el hacha a la raíz profunda de la naturaleza
caída. Con este nuevo discernimiento y sensibilidad,
el buscador ferviente pronto es apartado de toda dependencia carnal,
o de esta o aquella cosa,
y se levanta un clamor que llega hasta el oído de la Omnipotencia.
Desde las profundidades de un espíritu contrito,
el ojo del alma es entonces dirigido hacia Aquel que mora en los cielos, es decir,
hacia Aquel que permanece como el Sumo Sacerdote de Su iglesia,
y que sólo comunica una cosa necesaria, la cual es,
"`el _poder_ de una vida indestructible.`"^
footnote:[Hebreos 7:16]
Por lo tanto, el anhelo real y constante del alma por la pureza celestial,
se convierte en su capacidad para la verdadera iluminación,
y en su camino seguro hacia ella.
Y cuando esto va acompañado por verdadera rendición y sumisión
de la voluntad de la criatura a la del Creador,
en la que ambas se convierten en "`un espíritu,`" tiene la promesa
del verdadero discernimiento del propio Cristo que dijo:
"`__El que quiera hacer la voluntad de Dios,__ conocerá la doctrina,`"^
footnote:[Juan 7:17]
etc.

Encuentra aquí, mi querido amigo, tu escuela y tu verdadero ejercicio en ella,
si deseas avanzar en el conocimiento y experiencia cristianos reales.
Medita profundamente estas palabras de tu Salvador y somete tu
juicio a todas las consecuencias que necesariamente fluyen de ellas.
¡Oh, si hubieran más estudiantes en esta academia Cristiana interna,
habría entonces un beneficio real en la iglesia,
proveniente de la labor de los obreros que han sido enseñados por Dios!
Tales ministros,
que primero conocen en sus propias experiencias que Su reino (o
vida divina restaurada en el alma) "`no consiste en palabras,
sino en poder,`" expresarían una constante preocupación
de que la fe de sus oyentes se establezca sólo en este poder.
Y por otra parte, al ver claramente que un conocimiento laborioso,
intelectual y escolástico, revestido del más atractivo despliegue de retórica y oratoria,
no puede ir más lejos que la ministración de la letra,
voluntaria y naturalmente le dejarán esas actuaciones al sabio de este mundo.
Pero ¿dónde o en qué iglesia encontraremos a esos pastores que están dispuestos
a renunciar a todo el honor que se le prodiga a los dotados y elocuentes?
Si esos simples se levantaran de nuevo,
colocando toda la esperanza de ayudar a sus oyentes en el poder de Cristo,
temo que tales predicadores no tendrían muchos oyentes.

Tal vez te sorprenda un poco que hable así del estado presente de la iglesia.
Estoy consciente de que por lo general, se acepta una perspectiva diferente de las cosas,
pero eso no tambalea mi juicio en lo más mínimo.
No deseo sobrepasar los límites apropiados en este tema,
así que sólo tocaré una o dos señales más de degeneración,
que siento que son demasiado obvias como para pasarlas por alto.
¿Puede haber un engaño más fuerte de juicio que el de suponer que la búsqueda de riquezas,
honor y disfrute de los placeres de este mundo presente,
es compatible con el ejemplo de nuestro santo Señor y Salvador Jesucristo?
¿No es evidente, más bien,
que el primer y gran engañador y adversario de la humanidad
ha extendido su engañosa influencia en la mente humana,
al ver que la mayoría de los Cristianos profesantes creen
que han tomado a Cristo como su Legislador y modelo,
incluso cuando no sólo permiten sino que buscan facilidad y elegancia en sus viviendas,
honores y distinciones mundanos, exceso de pan,
y en algunas instancias "`abundancia de ociosidad`"^
footnote:[Ezequiel 16:49]
en sus vidas diarias?
Aunque tengamos ojos,
¿estamos todavía tan ciegos como para no ver la abierta y patente contradicción
que se exhibe entre las prácticas y costumbres de la época que son permitidas,
y las claras doctrinas y el ejemplo de nuestro Señor que renunció del mundo?
De seguro que los enemigos del Señor Jesús, los deístas e infieles de toda clase,
son más astutos que esto, y por lo tanto,
están ampliamente preparados para su crítica sarcástica y su burla.
"`Estos llamados peregrinos y extranjeros en la tierra,`" dicen,
"`parecen haberse acomodado a esta tierra extranjera,
aunque afirman que están muy lejos de su país natal y de la casa de su Padre.
En efecto, parecen sentarse aquí como nosotros,
cada uno bajo su propia viña y bajo su propia higuera.
Y aunque dicen que nosotros estaremos separados para siempre
al final del viaje--ellos resucitados en la gloria eterna,
y nosotros consignados a la vergüenza y eterno desdén--aun así,
parece que nosotros realmente viajamos en la misma dirección,
caminando en gran harmonía como amigos.`"

¡Oh! ¿Hasta cuándo tendrán los enemigos de la cruz de Cristo motivos para triunfar
así? ¿Hasta cuándo hablarán cosas orgullosas y despectivas contra el Señor,
por la oportunidad que les dan aquellos que,
por un lado profesan estar adheridos a las doctrinas
que demandan la crucifixión de la carne,
y por otro, son vistos haciendo plena provisión para la gratificación de sus deseos?
Cuando mis ojos se fijan en estas cosas, mi corazón se afecta, y mientras observo,
sentado solo como un gorrión en la azotea de la casa,
mi lenguaje interno a menudo concuerda con el del Profeta:
"`Faltó el misericordioso de la tierra, y ninguno hay recto entre los hombres,`"^
footnote:[Miqueas 7:2] etc.

Lo que se ha mencionado se relaciona con la práctica, pero, oh,
¿que se dirá con respecto a la doctrina, es decir,
de esa doctrina que se predica y es impuesta por los que asumen
el título de maestros evangélicos y ministros del evangelio?
Enseñan, por ejemplo, la conveniencia de usar la espada devoradora, sembrar desolación,
destrucción y todo tipo de horror entre las criaturas
inteligentes del Señor a través de la guerra,
y sugieren la compatibilidad de esto con el espíritu del manso, pasivo, amoroso,
sufriente Cordero de Dios, y con Sus preceptos y mandamientos.
O acusan al Dios de amor de parcialidad,
cuando declaran que Su oferta de redención en Cristo Jesús
es limitada--que sólo alcanza a los pocos escogidos;
mientras que el resto, millares de millares de cada generación,
nacidos herederos de la contaminación y miseria de Adán,
son dejados a perecer eternamente,
al nunca haber sido designados en el consejo secreto
de Dios para ser incluidos en Su pacto,
ni habérseles dado ese poder redentor que es el único
que puede librar de la muerte eterna.

Creo que estas son algunas de las señales de que el presente es un día oscuro--un día
en el que los hijos de la luz deberían aferrarse verdaderamente a la Palabra de verdad,
y no tener comunión con errores tan espantosos.
Me parece muy deseable que incluso los principiantes en religión
tengan una perspectiva clara del tiempo que les ha tocado en suerte.
Porque de hecho,
este mismo tipo de ceguera endureció tanto los corazones de los maestros,
gobernantes y profesantes del Judaísmo,
que los hizo insensibles a la fuerza combinada del poder milagroso,
sabiduría celestial y divino amor, unidos y continuamente manifestados en Jesucristo,
su Mesías desde hacía mucho tiempo prometido.
Al creer que la ortodoxia de ellos era iluminada y sus prácticas puras,
huyeron de Su luz condenatoria en sus propias consciencias.
Y aunque a veces se daban cuenta de que ningún hombre había hablado como Él lo hacía,
lo rechazaron todo, y despreciaron las doctrinas y milagros de su Redentor,
porque los principales fariseos y gobernantes "`no le creyeron.`"
Creo que debe ser obvio para todos los ojos que ven,
que la vieja levadura de los líderes religiosos prevalece demasiado hoy.
Descansar en las opiniones actuales de la ortodoxia
de cualquier comunidad a la que pertenezcamos,
es tan peligroso ahora como lo fue en el pasado.
Por tanto, no puedo dejar de pensar,
que una perspectiva clara de las "`señales de nuestros tiempos,`"
es necesaria para todo el que verdaderamente desea salir de la
Babilonia espiritual y dar pasos rectos hacia el monte Sion.

La parte final de esta comunicación no estaba en mi mente,
cuando me senté al principio a escribirte.
Si me pusiera a razonar sobre ella, mi fe posiblemente vacilaría un poco,
preguntándome si es comida apropiada para tu estado y crecimiento presentes.
Pero conservo la esperanza de que al menos,
resulte ser como '`el pan echado sobre las aguas;
el cual después de muchos días es hallado;`'^
footnote:[Eclesiastés 11:1]
y en esa esperanza lo dejo a tu seria consideración. Un tabernáculo débil y aun debilitándose,
me hace admitir la posibilidad de que esta sea la
última señal de mi amor cristiano hacia ti,
mi querido amigo.
Le he dado libertad a mi pluma,
y no he retenido nada que creyera que pudiera serte
de provecho para ti ahora o en el futuro.
¡Acepta, por tanto, esta palabra de exhortación,
y que el Padre de las luces la bendiga también para tu entendimiento y
tu corazón! ¡Que Él te capacite y prepare para recibir de esa unción que
hace que la enseñanza a través de instrumentos sea innecesaria,
es decir, para recibir la Verdad viva misma, sin mezcla e infalible!
A Aquel, y a la Palabra de Su gracia,
que es lo único que puede '`edificarte,`' debo encomendarte ahora.
¡Te ruego que seas fiel a tu Dios!
Has oído Su llamado a la santidad;
has sentido y te has regocijado en Sus persuasiones de tierno amor.
Deseo que Él nunca te deje ni te desampare, hasta que haya hecho en ti y por ti,
todo lo que te hablaron los primeros suaves suspiros de Su Espíritu,
y que tú entonces deseaste tan fervientemente.

[.signed-section-signature]
William Lewis
